export const Productos = [
    {   id: '001',
        categoryId: 'anillos',
        imagen: 'anillos/wave.jpg',
        nombre: 'wave',
        precio: 1100,
    },{
        id: "002",
        categoryId: 'anillos',
        imagen: 'anillos/camboya.jpg',
        nombre: 'camboya',
        precio: 1600,
    },{
        id: "003",
        categoryId: 'anillos',
        imagen: 'anillos/moon.jpg',
        nombre: 'moon',
        precio: 1000,
    },{
        id: "004",
        categoryId: 'anillos',
        imagen: 'anillos/world.jpg',
        nombre: 'world',
        precio: 1200,
    },{
        id: "005",
        categoryId: 'anillos',
        imagen: 'anillos/bali.jpg',
        nombre: 'bali',
        precio: 1400,
    },{
        id: "006",
        categoryId: 'anillos',
        imagen: 'anillos/shell.jpg',
        nombre: 'shell',
        precio: 1500,
    },{
        id: "007",
        categoryId: 'anillos',
        imagen: 'anillos/elephants.jpg',
        nombre: 'elephants',
        precio: 1550,
    },{
        id: "008",
        categoryId: 'anillos',
        imagen: 'anillos/phuket.jpg',
        nombre: 'phuket',
        precio: 1750,
    },{
        id: "009",
        categoryId: 'anillos',
        imagen: 'anillos/whale.jpg',
        nombre: 'whale',
        precio: 1350,
    },{
        id: "010",
        categoryId: 'anillos',
        imagen: 'anillos/mandala.jpg',
        nombre: 'mandala',
        precio: 1200,
    },{
        id: "011",
        categoryId: 'anillos',
        imagen: 'anillos/feather.jpg',
        nombre: 'feather',
        precio: 1700,
    },{
        id: "012",
        categoryId: 'anillos',
        imagen: 'anillos/zodiac.jpg',
        nombre: 'zodiac',
        precio: 1000,
    },{
        id: "013",
        categoryId: 'anillos',
        imagen: 'anillos/midiSeaTurtle.jpg',
        nombre: 'midi sea turtle',
        precio: 1000,
    },{
        id: "014",
        categoryId: 'anillos',
        imagen: 'anillos/midiAtenas.jpg',
        nombre: 'midi atenas',
        precio: 800,
    },{
        id: "015",
        categoryId: 'anillos',
        imagen: 'anillos/midiStarfish.jpg',
        nombre: 'midi starfish',
        precio: 900,
    },{
        id: "016",
        categoryId: 'anillos',
        imagen: 'anillos/midiBeachMoon.jpg',
        nombre: 'midi beach moon',
        precio: 900,
    },{ 
        id: '017',
        categoryId:'collares',  
        imagen: 'collares/world.jpg',
        nombre: 'world',
        precio: 1600,
    },{
        id: '018',
        categoryId:'collares', 
        imagen: 'collares/marocco.jpg',
        nombre: 'marocco',
        precio: 2300,
    },{
        id: '019',
        categoryId:'collares', 
        imagen: 'collares/circle.jpg',
        nombre: 'circle',
        precio: 1500,
    },{
        id: '020',
        categoryId:'collares', 
        imagen: 'collares/whale.jpg',
        nombre: 'whale',
        precio: 1800,
    },{
        id: '021',
        categoryId:'collares', 
        imagen: 'collares/wave.jpg',
        nombre: 'wave',
        precio: 1600,
    },{
        id: '022',
        categoryId:'collares', 
        imagen: 'collares/sea.jpg',
        nombre: 'sea',
        precio: 1900,
    },{
        id: '023',
        categoryId:'collares', 
        imagen: 'collares/phuket.jpg',
        nombre: 'phuket',
        precio: 1900,
    },{
        id: '024',
        categoryId:'collares', 
        imagen: 'collares/chokerShell.jpg',
        nombre: 'choker shell',
        precio: 2200,
}
]
